flags: {}
extra-package-dbs: []
ghc-options:
  ! '*': -O1 -threaded -rtsopts -with-rtsopts=-N
packages:
- '.'
- /home/cody/source/frames-diff
- /home/cody/source/Frames
extra-deps:
- rapid-0.1.3
- tz-0.1.2.0
resolver: lts-7.14
